pluginPackages=io.github.somehussar.crystalgraphics.hotswap

# Disable unrelated framework plugins to avoid interference
disabledPlugins=Hibernate,Spring,ZK,Tomcat,Logback,Log4j2,Jersey,Jetty,MyFaces,Mojarra,OmniFaces,ELResolver,WildFlyELResolver,OsgiEquinox,Owb,OwbJakarta,Proxy,WebObjects,Weld,WeldJakarta,CxfJAXRS,FreeMarker,Undertow,MyBatis,IBatis
