package com.crystalgraphics.text.msdf;

import com.crystalgraphics.api.font.CgFont;
import com.crystalgraphics.msdfgen.FreeTypeMSDFIntegration;
import com.crystalgraphics.msdfgen.MSDFBitmap;
import com.crystalgraphics.msdfgen.MSDFGenerator;
import com.crystalgraphics.msdfgen.MSDFShape;
import com.crystalgraphics.msdfgen.MSDFTransform;

import java.util.ArrayList;
import java.util.List;
import java.util.Comparator;

/**
 * Measures how faithfully a distance field at a given {@link CgMsdfAtlasConfig#atlasScalePx()}
 * reproduces the true glyph outline once reconstructed the way the GPU reconstructs it.
 *
 * <h3>What this actually measures</h3>
 * <p>MSDF does not degrade gracefully. Below a certain field resolution the median-of-3
 * reconstruction stops being able to represent a feature at all, and the artifact is structural
 * rather than soft: counters fill in, thin strokes merge into their neighbours.
 *
 * <p>Two numbers come out, and <strong>the topological one is the one that matters</strong>:
 * <ul>
 *   <li>{@link GlyphQuality#topologyDefects()} — counters that closed and strokes that merged.
 *       This is the artifact itself, counted.</li>
 *   <li>{@link GlyphQuality#mismatchRatio()} — the fraction of pixels that changed side. Useful
 *       as a continuous secondary signal, but <em>it cannot be used alone to decide a scale</em>.
 *       Measured on M+ 1p, a scale with visibly collapsed counters differed from a clean one by
 *       0.19% versus 0.11% of glyph area, because a counter is a minute fraction of a dense kanji.
 *       A threshold able to separate those would be fitted to that font and would measure nothing
 *       elsewhere.</li>
 * </ul>
 *
 * <h3>Why the reference is a high-resolution SDF, not a FreeType render</h3>
 * <p>The obvious ground truth is FreeType's own rasterizer, but comparing against it requires
 * mapping between FreeType's bearing-relative, y-down bitmap and msdfgen's translate-relative,
 * y-up one. That mapping is easy to get half a pixel wrong, and a half-pixel error inflates the
 * mismatch ratio for every candidate — quietly making an absolute threshold meaningless while
 * still looking plausible.
 *
 * <p>Instead the reference is a plain SDF generated by msdfgen at {@code evalPx}, thresholded at
 * 0.5. A true SDF evaluates exact distance at each pixel centre, so thresholding it <em>is</em> an
 * exact rasterization of the shape. Because it comes from the same generator with the same
 * {@link MSDFTransform} translate (which is in shape/em units and therefore scale-independent),
 * the reference grid and the reconstruction grid are co-registered by construction. There is no
 * alignment step that can silently be wrong.
 *
 * <p>This also drops font hinting from the comparison, which is correct: MSDF generation never
 * hints. The outline is the ground truth.
 *
 * <h3>Why evaluation happens at magnification</h3>
 * <p>The field is generated at {@code atlasScalePx} but reconstructed into a grid {@code evalPx}
 * per em — normally several times larger. Reconstructing at 1:1 would under-test badly, because
 * the artifacts only become visible when the field is magnified, which is precisely the world-text
 * case. Evaluating every candidate scale into the same {@code evalPx} grid has a second benefit:
 * mismatch ratios from different candidates share a denominator and are directly comparable.
 * Evaluated at the candidate's own box size they would not be.
 *
 * <h3>What this is not</h3>
 * <p>It measures one font against itself. It cannot rank two <em>different</em> fonts, because
 * edge-position error scales with a glyph's perimeter-to-ink ratio — a property of letterform
 * shape, not of reconstruction quality. Measured, that made a Latin text face score worse than
 * dense CJK at equal scale, which is obviously wrong. An earlier attempt to derive a per-font
 * atlas scale from these numbers foundered on exactly that and was removed; the atlas now uses a
 * single scale for every font, and the memory question was solved by sharing atlases instead.
 */
public final class CgMsdfQualityProbe {

    /**
     * Reconstruction resolution in px/em.
     *
     * <p><strong>Any scale compared against another must divide this exactly.</strong> The probe
     * uses a whole magnification (a fractional one misregisters the two grids), so a scale that does
     * not divide this is evaluated at a different resolution than its neighbours — and since the
     * speckle cutoff and therefore the reference topology depend on resolution, such scales are not
     * comparable to each other. 240 divides by 30, 40, 48, 60, 80 and 120. The obvious ladder
     * {32, 64, 96, 128} does not, and produced a non-monotone quality curve until it was caught.
     */
    public static final int DEFAULT_EVAL_PX = 240;

    /** Coverage value separating inside from outside on both sides of the comparison. */
    public static final float INSIDE_THRESHOLD = 0.5f;

    /**
     * Numeric format the atlas texture stores the field in — the thing being compared when asking
     * whether {@code RGBA16F} buys anything over {@code RGBA8}.
     */
    public enum FieldStorage {
        /** {@code RGBA16F}: the field is used at generator precision, as the atlas allocates today. */
        HALF_FLOAT,
        /**
         * {@code RGBA8}: clamp to [0,1] and quantise to 256 levels before any filtering — exactly
         * what an 8-bit unorm texture does, and what msdf-atlas-gen's default PNG output produces.
         */
        UNORM8
    }

    /**
     * Clamps and quantises a field in place to 256 levels, modelling an 8-bit unorm texture.
     *
     * <p>Applied to the field <em>before</em> reconstruction rather than after, because a real
     * {@code RGBA8} texture quantises on upload and then filters the already-quantised texels.
     * Quantising the filtered result instead would flatter 8-bit by hiding the interaction between
     * quantisation and bilinear interpolation.
     */
    private static void quantiseToUnorm8(float[] pixels) {
        for (int i = 0; i < pixels.length; i++) {
            float v = pixels[i];
            if (v < 0.0f) v = 0.0f;
            else if (v > 1.0f) v = 1.0f;
            pixels[i] = Math.round(v * 255.0f) / 255.0f;
        }
    }

    /**
     * Reconstructs the inside/outside mask from the field the way the GPU does: bilinear filtering
     * of the stored texels, then median of the three channels against 0.5.
     *
     * <p>This replaces msdfgen's own {@code renderSdf}, for a practical reason and a correctness
     * one. Practical: {@code MSDFBitmap.getPixelData()} hands back a copy and there is no setter,
     * so a quantised field cannot be pushed back into native memory for {@code renderSdf} to read.
     * Correctness: the shader's coverage is
     * {@code clamp(screenPxRange * (median - 0.5) + 0.5, 0, 1)}, and thresholding that at 0.5
     * reduces exactly to {@code median >= 0.5} for any positive range — so the inside/outside
     * decision measured here is the shader's own, independent of pxRange and of msdfgen's CPU
     * renderer.
     */
    private static boolean[] reconstruct(float[] field, int fieldWidth, int fieldHeight, int channels,
                                         int outWidth, int outHeight) {
        boolean[] inside = new boolean[outWidth * outHeight];
        double scaleX = (double) fieldWidth / (double) outWidth;
        double scaleY = (double) fieldHeight / (double) outHeight;

        for (int y = 0; y < outHeight; y++) {
            double sy = (y + 0.5) * scaleY - 0.5;
            int y0 = (int) Math.floor(sy);
            double fy = sy - y0;
            int y0c = clamp(y0, fieldHeight);
            int y1c = clamp(y0 + 1, fieldHeight);

            for (int x = 0; x < outWidth; x++) {
                double sx = (x + 0.5) * scaleX - 0.5;
                int x0 = (int) Math.floor(sx);
                double fx = sx - x0;
                int x0c = clamp(x0, fieldWidth);
                int x1c = clamp(x0 + 1, fieldWidth);

                float r = bilinear(field, channels, fieldWidth, x0c, x1c, y0c, y1c, fx, fy, 0);
                float g = bilinear(field, channels, fieldWidth, x0c, x1c, y0c, y1c, fx, fy, 1);
                float b = bilinear(field, channels, fieldWidth, x0c, x1c, y0c, y1c, fx, fy, 2);
                inside[y * outWidth + x] = median(r, g, b) >= INSIDE_THRESHOLD;
            }
        }
        return inside;
    }

    private static float bilinear(float[] field, int channels, int fieldWidth,
                                  int x0, int x1, int y0, int y1, double fx, double fy, int channel) {
        float v00 = field[(y0 * fieldWidth + x0) * channels + channel];
        float v10 = field[(y0 * fieldWidth + x1) * channels + channel];
        float v01 = field[(y1 * fieldWidth + x0) * channels + channel];
        float v11 = field[(y1 * fieldWidth + x1) * channels + channel];
        double top = v00 + (v10 - v00) * fx;
        double bottom = v01 + (v11 - v01) * fx;
        return (float) (top + (bottom - top) * fy);
    }

    private static float median(float a, float b, float c) {
        return Math.max(Math.min(a, b), Math.min(Math.max(a, b), c));
    }

    private static int clamp(int v, int size) {
        return v < 0 ? 0 : (v >= size ? size - 1 : v);
    }

    private CgMsdfQualityProbe() {
    }

    /**
     * Result of probing one glyph at one candidate scale.
     *
     * @param glyphId        the glyph probed
     * @param mismatchRatio  disagreeing pixels as a fraction of the reference glyph's <em>ink</em>
     *                       area — not of the box, which is not comparable across scripts
     * @param evaluatedPixels size of the comparison grid
     * @param edgeCount      outline edge count, retained because it is the selection signal
     * @param empty          whitespace or degenerate glyph — carries no quality information
     */
    public record GlyphQuality(int glyphId, float mismatchRatio, int evaluatedPixels,
                               int edgeCount, boolean empty,
                               int holesReference, int holesReconstructed,
                               int strokesReference, int strokesReconstructed) {

        static GlyphQuality empty(int glyphId, int edgeCount) {
            return new GlyphQuality(glyphId, 0.0f, 0, edgeCount, true, 0, 0, 0, 0);
        }

        /** An empty glyph never constrains the atlas scale. */
        public boolean informative() {
            return !empty && evaluatedPixels > 0;
        }

        /**
         * Number of enclosed counters that closed up, plus separate strokes that merged into one
         * another — the two structural ways MSDF fails when the field runs out of resolution.
         *
         * <p>Only losses count. A reconstruction with an <em>extra</em> hole is speckle from
         * threshold noise, which is a cosmetic complaint rather than the collapse this is looking
         * for, and folding it in here would make the signal jitter.
         */
        public int topologyDefects() {
            return Math.max(0, holesReference - holesReconstructed)
                    + Math.max(0, strokesReference - strokesReconstructed);
        }
    }

    /**
     * Probes a single glyph at the scale carried by {@code config}.
     *
     * <p>Never throws for glyph-level problems — a glyph that cannot be loaded or has no area
     * comes back {@link GlyphQuality#empty()}, because one unloadable glyph must not abort a
     * whole-font scale derivation.
     *
     * @param msdfFont the msdfgen-side font handle
     * @param glyphId  glyph index (not a code point)
     * @param config   the candidate configuration; only scale, range and generation parameters matter
     * @param evalPx   reconstruction resolution in px/em, normally {@link #DEFAULT_EVAL_PX}
     * @return the measurement, never {@code null}
     */
    public static GlyphQuality probe(FreeTypeMSDFIntegration.Font msdfFont,
                                     int glyphId,
                                     CgMsdfAtlasConfig config,
                                     int evalPx) {
        return probe(msdfFont, glyphId, config, evalPx, FieldStorage.HALF_FLOAT);
    }

    /**
     * Probes a single glyph, modelling the atlas texture format via {@code storage}.
     *
     * @param storage numeric format the field is stored in before reconstruction
     */
    public static GlyphQuality probe(FreeTypeMSDFIntegration.Font msdfFont,
                                     int glyphId,
                                     CgMsdfAtlasConfig config,
                                     int evalPx,
                                     FieldStorage storage) {
        if (msdfFont == null) {
            throw new IllegalArgumentException("msdfFont must not be null");
        }
        if (config == null) {
            throw new IllegalArgumentException("config must not be null");
        }
        if (evalPx <= 0) {
            throw new IllegalArgumentException("evalPx must be > 0, got " + evalPx);
        }

        FreeTypeMSDFIntegration.GlyphData glyphData;
        try {
            glyphData = msdfFont.loadGlyphByIndex(glyphId, FreeTypeMSDFIntegration.FONT_SCALING_EM_NORMALIZED);
        } catch (RuntimeException e) {
            return GlyphQuality.empty(glyphId, 0);
        }

        MSDFShape shape = glyphData.getShape();
        try {
            shape.normalize();
            int edgeCount = shape.getEdgeCount();
            CgMsdfGenerator.applyEdgeColoring(shape, config);

            double[] bounds = shape.getBounds();
            CgMsdfGlyphLayout layout = CgMsdfGlyphLayout.compute(
                    bounds[0], bounds[1], bounds[2], bounds[3],
                    config.atlasScalePx(), config.pxRange(),
                    config.miterLimit(), config.alignOriginX(), config.alignOriginY());
            if (layout.isEmpty() || layout.getBoxWidth() <= 0 || layout.getBoxHeight() <= 0) {
                return GlyphQuality.empty(glyphId, edgeCount);
            }

            return compareAtScale(shape, layout, config, glyphId, edgeCount, evalPx, storage);
        } catch (RuntimeException e) {
            return GlyphQuality.empty(glyphId, 0);
        } finally {
            shape.free();
        }
    }

    /**
     * Generates the candidate field, reconstructs it magnified, generates the reference at the same
     * magnification, and counts disagreeing pixels.
     */
    private static GlyphQuality compareAtScale(MSDFShape shape,
                                               CgMsdfGlyphLayout layout,
                                               CgMsdfAtlasConfig config,
                                               int glyphId,
                                               int edgeCount,
                                               int evalPx,
                                               FieldStorage storage) {
        int boxWidth = layout.getBoxWidth();
        int boxHeight = layout.getBoxHeight();

        // The magnification MUST be an exact integer. Rounding an arbitrary ratio to whole pixels
        // leaves the reconstruction grid covering a very slightly different em extent than the
        // reference, and a sub-pixel misregistration costs mismatch along the entire outline — an
        // error proportional to perimeter, so it hits exactly the dense glyphs this probe exists to
        // judge. Measured, it made scale 96 score worse than 32 purely because 256/96 is not whole.
        // With an integer factor both grids span [-translate, box/scale - translate] identically.
        int magnification = Math.max(1, (int) Math.round(evalPx / (double) config.atlasScalePx()));
        int effectiveEvalPx = config.atlasScalePx() * magnification;
        int evalWidth = boxWidth * magnification;
        int evalHeight = boxHeight * magnification;

        // Both transforms share translate (shape/em units, scale-independent) and range, so the
        // low-res field, its reconstruction, and the reference all cover the identical em region.
        MSDFTransform fieldTransform = new MSDFTransform()
                .scale(layout.getScale())
                .translate(layout.getTranslateX(), layout.getTranslateY())
                .range(-layout.getRangeInShapeUnits(), layout.getRangeInShapeUnits());
        MSDFTransform referenceTransform = new MSDFTransform()
                .scale(effectiveEvalPx)
                .translate(layout.getTranslateX(), layout.getTranslateY())
                .range(-layout.getRangeInShapeUnits(), layout.getRangeInShapeUnits());

        MSDFBitmap field = MSDFBitmap.allocMsdf(boxWidth, boxHeight);
        MSDFBitmap reference = MSDFBitmap.allocSdf(evalWidth, evalHeight);
        try {
            MSDFGenerator.generateMsdf(field, shape, fieldTransform,
                    config.overlapSupport(),
                    config.errorCorrectionMode(),
                    config.distanceCheckMode(),
                    config.minDeviationRatio(),
                    config.minImproveRatio());

            // Exact rasterization: a true SDF holds signed distance at each pixel centre, so the
            // 0.5 crossing is the outline itself.
            MSDFGenerator.generateSdf(reference, shape, referenceTransform);

            float[] fieldPixels = field.getPixelData();
            if (storage == FieldStorage.UNORM8) {
                quantiseToUnorm8(fieldPixels);
            }

            float[] referencePixels = reference.getPixelData();
            int total = evalWidth * evalHeight;
            if (total <= 0 || referencePixels.length < total) {
                return GlyphQuality.empty(glyphId, edgeCount);
            }

            boolean[] insideReconstructed = reconstruct(fieldPixels, boxWidth, boxHeight,
                    field.getChannelCount(), evalWidth, evalHeight);
            boolean[] insideReference = new boolean[total];
            int mismatches = 0;
            int referenceInk = 0;
            for (int i = 0; i < total; i++) {
                insideReference[i] = referencePixels[i] >= INSIDE_THRESHOLD;
                if (insideReference[i]) {
                    referenceInk++;
                }
                if (insideReconstructed[i] != insideReference[i]) {
                    mismatches++;
                }
            }

            // Normalise by the glyph's own ink, not by the box.
            //
            // The box is the glyph bounds padded by the distance range, and how much of it the glyph
            // actually fills varies enormously between scripts: a dense kanji fills most of its box,
            // a Latin 'l' almost none of it. Dividing by box area therefore reports the same physical
            // edge error as a far larger number for the Latin glyph, which makes scores incomparable
            // between fonts — measured, it ranked IBM Plex Sans as needing a *higher* atlas scale
            // than dense CJK. Ink-relative error is what "how wrong does this glyph look" actually
            // means, and it is comparable across scripts.
            int denominator = referenceInk > 0 ? referenceInk : total;

            int minFeatureArea = minFeatureArea(effectiveEvalPx);
            int holesReference = countHoles(insideReference, evalWidth, evalHeight, minFeatureArea);
            int holesReconstructed = countHoles(insideReconstructed, evalWidth, evalHeight, minFeatureArea);
            int strokesReference = countStrokes(insideReference, evalWidth, evalHeight, minFeatureArea);
            int strokesReconstructed = countStrokes(insideReconstructed, evalWidth, evalHeight, minFeatureArea);

            return new GlyphQuality(glyphId, (float) mismatches / (float) denominator, total, edgeCount, false,
                    holesReference, holesReconstructed, strokesReference, strokesReconstructed);
        } finally {
            reference.free();
            field.free();
        }
    }

    /**
     * Diameter, as a fraction of em, below which a blob is treated as threshold speckle rather than
     * a real counter or stroke. Chosen well under the smallest counter any legible face uses and
     * well over the 0.5-crossing jitter that produces one- and two-pixel specks.
     */
    private static final double MIN_FEATURE_EM = 1.0 / 48.0;

    /**
     * Smallest blob counted as a real feature, in eval pixels, for a grid of {@code effectiveEvalPx}
     * per em.
     *
     * <p><strong>Must be em-proportional, not magnification-proportional.</strong> The cutoff is
     * applied to the reference as well as the reconstruction, so if it varies with the candidate
     * scale then the reference topology varies too and the difference between them stops measuring
     * reconstruction quality. Scaling it by magnification did exactly that: the cutoff swung from 36
     * eval pixels at scale 32 to 4 at scale 80, letting speckle into the reference at the loose end
     * and making scale 80 score worse than 64 — the opposite of physical.
     */
    private static int minFeatureArea(int effectiveEvalPx) {
        int diameter = (int) Math.round(effectiveEvalPx * MIN_FEATURE_EM);
        return Math.max(4, diameter * diameter);
    }

    /** Connected foreground regions — distinct strokes. Merging two of them is a structural loss. */
    private static int countStrokes(boolean[] mask, int width, int height, int minArea) {
        return countRegions(mask, width, height, minArea, true, false);
    }

    /**
     * Enclosed background regions — counters. A counter filling in is the single most recognisable
     * MSDF underscale artifact, and it is invisible to an area-based metric because a counter is a
     * tiny fraction of a dense glyph's area.
     *
     * <p>Background regions touching the image border are the outside of the glyph, not counters,
     * so they are excluded.
     */
    private static int countHoles(boolean[] mask, int width, int height, int minArea) {
        return countRegions(mask, width, height, minArea, false, true);
    }

    /**
     * Iterative flood fill over {@code mask}, counting regions of {@code target} value that reach
     * {@code minArea}.
     *
     * <p>Foreground uses 8-connectivity and background 4-connectivity — the standard pairing that
     * keeps diagonal configurations from being counted as connected on both sides at once, which
     * would let a stroke and the hole it encloses both appear joined.
     *
     * @param excludeBorderTouching drop regions reaching the image edge (used for holes)
     */
    private static int countRegions(boolean[] mask, int width, int height, int minArea,
                                    boolean target, boolean excludeBorderTouching) {
        boolean[] visited = new boolean[mask.length];
        int[] stack = new int[mask.length];
        boolean eightConnected = target;
        int regions = 0;

        for (int seed = 0; seed < mask.length; seed++) {
            if (visited[seed] || mask[seed] != target) {
                continue;
            }
            int stackSize = 0;
            stack[stackSize++] = seed;
            visited[seed] = true;
            int area = 0;
            boolean touchesBorder = false;

            while (stackSize > 0) {
                int index = stack[--stackSize];
                int x = index % width;
                int y = index / width;
                area++;
                if (x == 0 || y == 0 || x == width - 1 || y == height - 1) {
                    touchesBorder = true;
                }
                for (int dy = -1; dy <= 1; dy++) {
                    for (int dx = -1; dx <= 1; dx++) {
                        if (dx == 0 && dy == 0) {
                            continue;
                        }
                        if (!eightConnected && dx != 0 && dy != 0) {
                            continue;
                        }
                        int nx = x + dx;
                        int ny = y + dy;
                        if (nx < 0 || ny < 0 || nx >= width || ny >= height) {
                            continue;
                        }
                        int neighbour = ny * width + nx;
                        if (!visited[neighbour] && mask[neighbour] == target) {
                            visited[neighbour] = true;
                            stack[stackSize++] = neighbour;
                        }
                    }
                }
            }

            if (area >= minArea && !(excludeBorderTouching && touchesBorder)) {
                regions++;
            }
        }
        return regions;
    }


    // ── Whole-font evaluation ────────────────────────────────────────────

    /**
     * Aggregate quality of one configuration across a glyph sample.
     *
     * @param worstMismatch   highest ink-relative area error seen
     * @param worstGlyphId    glyph that produced it — the one to look at when a result surprises
     * @param glyphsProbed    informative (non-empty) glyphs actually measured
     * @param defectiveGlyphs glyphs showing at least one closed counter or merged stroke
     * @param totalDefects    sum of those defects
     * @param referenceFeatures total holes + strokes found in the reference; a self-check, since
     *                        the reference is the same shape at the same resolution for every
     *                        configuration in a run and must therefore not vary between them
     */
    public record FieldQuality(float worstMismatch, int worstGlyphId, int glyphsProbed,
                               int defectiveGlyphs, int totalDefects, int referenceFeatures) {
    }

    /** Probes every glyph in {@code glyphIds} and aggregates the result. */
    public static FieldQuality evaluate(FreeTypeMSDFIntegration.Font msdfFont,
                                        CgMsdfAtlasConfig config,
                                        int[] glyphIds,
                                        int evalPx,
                                        FieldStorage storage) {
        float worst = 0.0f;
        int worstGlyphId = -1;
        int probed = 0;
        int defectiveGlyphs = 0;
        int totalDefects = 0;
        int referenceFeatures = 0;

        for (int glyphId : glyphIds) {
            GlyphQuality quality = probe(msdfFont, glyphId, config, evalPx, storage);
            if (!quality.informative()) {
                continue;
            }
            probed++;
            referenceFeatures += quality.holesReference() + quality.strokesReference();
            if (quality.mismatchRatio() > worst) {
                worst = quality.mismatchRatio();
                worstGlyphId = quality.glyphId();
            }
            int defects = quality.topologyDefects();
            if (defects > 0) {
                defectiveGlyphs++;
                totalDefects += defects;
            }
        }
        return new FieldQuality(worst, worstGlyphId, probed, defectiveGlyphs, totalDefects, referenceFeatures);
    }

    /**
     * Picks the glyphs most worth probing: a percentile band of outline complexity, near the top
     * but not at it.
     *
     * <p>Edge count is a poor predictor of the scale a font <em>needs</em> — it measures complexity
     * where MSDF fails on thinness, and those diverge badly between scripts. Within one font,
     * though, where stroke weight is roughly consistent by design, it ranks glyphs by how much
     * detail has to survive, and that is all this needs to do.
     *
     * <p>The band matters. The absolute top of an 8.5k-glyph CJK face is pathological outliers that
     * retain defects even at 120 px/em and would dominate any measurement; a uniform random sample
     * is mostly kana and Latin that survive anything. Sampling between the two lands on glyphs that
     * are genuinely hard and genuinely used.
     *
     * @param percentileLow  lower edge of the band, e.g. {@code 0.88}
     * @param percentileHigh upper edge, e.g. {@code 0.98}
     * @param maxScanned     ceiling on glyphs whose edge count is measured; past this the scan
     *                       strides evenly rather than visiting every glyph
     */
    public static int[] selectDenseGlyphs(CgFont font, int count, float percentileLow,
                                          float percentileHigh, int maxScanned) {
        if (font == null || font.isDisposed()) {
            throw new IllegalArgumentException("font must not be null or disposed");
        }
        if (count <= 0) {
            throw new IllegalArgumentException("count must be > 0, got " + count);
        }
        if (percentileLow < 0.0f || percentileLow >= percentileHigh || percentileHigh > 1.0f) {
            throw new IllegalArgumentException("percentiles must satisfy 0 <= low < high <= 1");
        }
        FreeTypeMSDFIntegration.Font msdfFont = font.getMsdfFont();
        if (msdfFont == null) {
            throw new IllegalStateException("MSDF font integration unavailable for " + font.getKey());
        }

        int glyphCount = Math.max(1, font.getFtFace().getNumGlyphs());
        int stride = Math.max(1, (int) Math.ceil(glyphCount / (double) maxScanned));

        List<int[]> scanned = new ArrayList<>();
        for (int glyphId = 1; glyphId < glyphCount; glyphId += stride) {
            int edges = edgeCount(msdfFont, glyphId);
            if (edges > 0) {
                scanned.add(new int[]{glyphId, edges});
            }
        }
        if (scanned.isEmpty()) {
            return new int[0];
        }

        scanned.sort(Comparator.comparingInt(entry -> entry[1]));
        int total = scanned.size();
        int low = clampIndex((int) Math.floor(total * percentileLow), total);
        int high = clampIndex((int) Math.floor(total * percentileHigh), total);
        if (high <= low) {
            high = Math.min(total - 1, low + 1);
        }

        int band = high - low + 1;
        int take = Math.min(count, band);
        int[] sample = new int[take];
        for (int i = 0; i < take; i++) {
            int offset = take == 1 ? 0 : (int) Math.round(i * (band - 1) / (double) (take - 1));
            sample[i] = scanned.get(low + offset)[0];
        }
        return sample;
    }

    private static int clampIndex(int index, int total) {
        return Math.max(0, Math.min(total - 1, index));
    }

    /**
     * Outline edge count for a glyph, or {@code 0} if it cannot be loaded.
     *
     * <p>Used only to <em>choose</em> which glyphs to probe. It is a poor absolute predictor of the
     * required scale — a hairline serif has few edges and needs a very high scale, a heavy
     * decorative face has many and needs a low one — but within a single font, where stroke weight
     * is roughly consistent by design, it ranks glyphs by how much detail must survive. That is all
     * the selection step needs.
     */
    public static int edgeCount(FreeTypeMSDFIntegration.Font msdfFont, int glyphId) {
        FreeTypeMSDFIntegration.GlyphData glyphData;
        try {
            glyphData = msdfFont.loadGlyphByIndex(glyphId, FreeTypeMSDFIntegration.FONT_SCALING_EM_NORMALIZED);
        } catch (RuntimeException e) {
            return 0;
        }
        MSDFShape shape = glyphData.getShape();
        try {
            return shape.getEdgeCount();
        } catch (RuntimeException e) {
            return 0;
        } finally {
            shape.free();
        }
    }
}
