package io.github.somehussar.crystalgraphics.api.texture;

import lombok.Builder;
import lombok.Getter;

import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL12;
import org.lwjgl.opengl.GL13;
import org.lwjgl.opengl.GL14;
import org.lwjgl.opengl.GL30;

/**
 * Immutable specification for a GL texture: format + sampler params + optional shadow compare.
 *
 * <p>Built via Lombok {@link Builder}. The format triple (internalFormat, baseFormat, type)
 * is encoded as a single {@link CgTextureType} enum constant — no raw int fields, no hex
 * literals. Sampler parameters ({@link #minFilter}, {@link #magFilter},
 * {@link #wrapS}/{@link #wrapT}/{@link #wrapR}) default to safe choices: {@code GL_LINEAR}
 * filtering and {@code GL_CLAMP_TO_EDGE} wrapping.</p>
 *
 * <p>Shadow depth comparison ({@link #compareMode}, {@link #compareFunc}) defaults to
 * {@code GL_NONE} (disabled). Enable only for shadow map PCF sampling via
 * {@link #DEPTH24_SHADOW}.</p>
 *
 * <p>Mipmap policy is controlled by {@link CgMipmapConfig}, defaulting to
 * {@link CgMipmapConfig#NONE}.</p>
 *
 * <h3>Pre-built constants</h3>
 * <ul>
 *   <li>{@link #RGBA8_LINEAR} — 8-bit RGBA, linear filter, clamp wrap</li>
 *   <li>{@link #RGBA8_NEAREST} — 8-bit RGBA, nearest filter (pixel art)</li>
 *   <li>{@link #RGBA8_LINEAR_CLAMP_BORDER} — 8-bit RGBA, linear, clamp-to-border</li>
 *   <li>{@link #RGBA8_NEAREST_CLAMP_BORDER} — 8-bit RGBA, nearest, clamp-to-border</li>
 *   <li>{@link #RGBA8_LINEAR_REPEAT} — 8-bit RGBA, linear, repeat</li>
 *   <li>{@link #RGBA8_NEAREST_REPEAT} — 8-bit RGBA, nearest, repeat</li>
 *   <li>{@link #RGBA8_LINEAR_MIRRORED} — 8-bit RGBA, linear, mirrored-repeat</li>
 *   <li>{@link #RGBA8_NEAREST_MIRRORED} — 8-bit RGBA, nearest, mirrored-repeat</li>
 *   <li>{@link #R8_LINEAR_REPEAT} — 8-bit R, linear, repeat</li>
 *   <li>{@link #R8_NEAREST_REPEAT} — 8-bit R, nearest, repeat</li>
 *   <li>{@link #RGBA16F_LINEAR} — 16-bit float RGBA, linear filter (HDR)</li>
 *   <li>{@link #DEPTH24_SHADOW} — 24-bit depth with hardware PCF (shadow map sampling)</li>
 * </ul>
 *
 * <p>Also exposes the GL-side helper {@link #applyTo(int)} which writes this spec's
 * filter/wrap/compare params to the currently bound texture.</p>
 */
@Getter
@Builder(toBuilder = true)
public final class CgTextureSpec {

    // ── Format — CgTextureFormatSpec is gone; one typed field replaces the triple ──

    /**
     * The texture format. Required — no {@code @Builder.Default}.
     * Controls {@link #getGlInternalFormat()}, {@link #getGlBaseFormat()},
     * and {@link #getGlType()} via delegate methods.
     */
    private final CgTextureType type;

    // Convenience delegates so downstream call sites stay stable after the format refactor.
    // These are explicit methods — NOT generated by @Getter (which only covers fields).

    /** Returns {@code type.glInternalFormat} (e.g. {@code GL_RGBA8}). */
    public int getGlInternalFormat() { return type.glInternalFormat; }
    /** Returns {@code type.glBaseFormat} (e.g. {@code GL_RGBA}). */
    public int getGlBaseFormat()     { return type.glBaseFormat; }
    /** Returns {@code type.glType} (e.g. {@code GL_UNSIGNED_BYTE}). */
    public int getGlType()           { return type.glType; }

    // ── Mipmap ──────────────────────────────────────────────────────────────────

    /** Mipmap policy. Defaults to {@link CgMipmapConfig#NONE} (disabled). */
    @Builder.Default
    private final CgMipmapConfig mipmaps = CgMipmapConfig.NONE;

    // ── Sampler params ───────────────────────────────────────────────────────────

    /** Minification filter. Default {@code GL_LINEAR}. */
    @Builder.Default
    private final int minFilter = GL11.GL_LINEAR;

    /** Magnification filter. Default {@code GL_LINEAR}. */
    @Builder.Default
    private final int magFilter = GL11.GL_LINEAR;

    /** Wrap mode for the S coordinate. Default {@code GL_CLAMP_TO_EDGE}. */
    @Builder.Default
    private final int wrapS = GL12.GL_CLAMP_TO_EDGE;

    /** Wrap mode for the T coordinate. Default {@code GL_CLAMP_TO_EDGE}. */
    @Builder.Default
    private final int wrapT = GL12.GL_CLAMP_TO_EDGE;

    /** Wrap mode for the R coordinate (3D / 2D-array targets only). Default {@code GL_CLAMP_TO_EDGE}. */
    @Builder.Default
    private final int wrapR = GL12.GL_CLAMP_TO_EDGE;

    // ── Shadow comparison (depth textures only) ──────────────────────────────────

    /**
     * Shadow compare mode. Default {@code GL_NONE} (disabled).
     * Set to {@code GL_COMPARE_R_TO_TEXTURE} to enable PCF shadow sampling.
     * Only meaningful for depth-format textures; ignored by the GL driver for color formats.
     */
    @Builder.Default
    private final int compareMode = GL11.GL_NONE;

    /**
     * Shadow compare function. Default {@code GL_LEQUAL}.
     * Only applied when {@link #compareMode} != {@code GL_NONE}.
     */
    @Builder.Default
    private final int compareFunc = GL11.GL_LEQUAL;

    // ── Pre-built constants (all via CgTextureType, zero hex) ───────────────────

    /** 8-bit RGBA, linear filtering, clamp-to-edge. The general default. */
    public static final CgTextureSpec RGBA8_LINEAR =
            CgTextureType.RGBA8.toTextureSpec();

    /** 8-bit RGBA with nearest filtering (pixel-art / sharp sprites). */
    public static final CgTextureSpec RGBA8_NEAREST = CgTextureSpec.builder()
            .type(CgTextureType.RGBA8)
            .minFilter(GL11.GL_NEAREST).magFilter(GL11.GL_NEAREST)
            .build();

    /** 8-bit RGBA, linear filtering, clamp-to-border. */
    public static final CgTextureSpec RGBA8_LINEAR_CLAMP_BORDER = CgTextureSpec.builder()
            .type(CgTextureType.RGBA8)
            .wrapS(GL13.GL_CLAMP_TO_BORDER).wrapT(GL13.GL_CLAMP_TO_BORDER).wrapR(GL13.GL_CLAMP_TO_BORDER)
            .build();

    /** 8-bit RGBA with nearest filtering, clamp-to-border. */
    public static final CgTextureSpec RGBA8_NEAREST_CLAMP_BORDER = CgTextureSpec.builder()
            .type(CgTextureType.RGBA8)
            .minFilter(GL11.GL_NEAREST).magFilter(GL11.GL_NEAREST)
            .wrapS(GL13.GL_CLAMP_TO_BORDER).wrapT(GL13.GL_CLAMP_TO_BORDER).wrapR(GL13.GL_CLAMP_TO_BORDER)
            .build();

    /** 8-bit RGBA, linear filtering, repeat. */
    public static final CgTextureSpec RGBA8_LINEAR_REPEAT = CgTextureSpec.builder()
            .type(CgTextureType.RGBA8)
            .wrapS(GL11.GL_REPEAT).wrapT(GL11.GL_REPEAT).wrapR(GL11.GL_REPEAT)
            .build();

    /** 8-bit RGBA with nearest filtering, repeat. */
    public static final CgTextureSpec RGBA8_NEAREST_REPEAT = CgTextureSpec.builder()
            .type(CgTextureType.RGBA8)
            .minFilter(GL11.GL_NEAREST).magFilter(GL11.GL_NEAREST)
            .wrapS(GL11.GL_REPEAT).wrapT(GL11.GL_REPEAT).wrapR(GL11.GL_REPEAT)
            .build();

    /** 8-bit RGBA, linear filtering, mirrored-repeat. */
    public static final CgTextureSpec RGBA8_LINEAR_MIRRORED = CgTextureSpec.builder()
            .type(CgTextureType.RGBA8)
            .wrapS(GL14.GL_MIRRORED_REPEAT).wrapT(GL14.GL_MIRRORED_REPEAT).wrapR(GL14.GL_MIRRORED_REPEAT)
            .build();

    /** 8-bit RGBA with nearest filtering, mirrored-repeat. */
    public static final CgTextureSpec RGBA8_NEAREST_MIRRORED = CgTextureSpec.builder()
            .type(CgTextureType.RGBA8)
            .minFilter(GL11.GL_NEAREST).magFilter(GL11.GL_NEAREST)
            .wrapS(GL14.GL_MIRRORED_REPEAT).wrapT(GL14.GL_MIRRORED_REPEAT).wrapR(GL14.GL_MIRRORED_REPEAT)
            .build();

    /** 8-bit R, linear filtering, repeat. For single-channel data (noise, masks, heightmaps). */
    public static final CgTextureSpec R8_LINEAR_REPEAT = CgTextureSpec.builder()
            .type(CgTextureType.R8)
            .wrapS(GL11.GL_REPEAT).wrapT(GL11.GL_REPEAT).wrapR(GL11.GL_REPEAT)
            .build();

    /** 8-bit R, nearest filtering, repeat. For single-channel data (noise, masks, heightmaps). */
    public static final CgTextureSpec R8_NEAREST_REPEAT = CgTextureSpec.builder()
            .type(CgTextureType.R8)
            .minFilter(GL11.GL_NEAREST).magFilter(GL11.GL_NEAREST)
            .wrapS(GL11.GL_REPEAT).wrapT(GL11.GL_REPEAT).wrapR(GL11.GL_REPEAT)
            .build();

    /** 16-bit float RGBA, linear filtering. HDR / intermediate render targets. */
    public static final CgTextureSpec RGBA16F_LINEAR =
            CgTextureType.RGBA16F.toTextureSpec();

    /**
     * 24-bit depth texture with hardware PCF shadow comparison ({@code GL_COMPARE_R_TO_TEXTURE},
     * {@code GL_LEQUAL}). Use for shadow map sampling in shaders via {@code sampler2DShadow}.
     *
     * <p>This is the ONLY pre-built spec with compare mode enabled.
     * {@link CgTextureType#toTextureSpec()} always returns a neutral (no-compare) spec.</p>
     */
    public static final CgTextureSpec DEPTH24_SHADOW = CgTextureSpec.builder()
            .type(CgTextureType.DEPTH24)
            .compareMode(GL14.GL_COMPARE_R_TO_TEXTURE)
            .compareFunc(GL11.GL_LEQUAL)
            .build();

    // ── GL-side helper ───────────────────────────────────────────────────────────

    /**
     * Applies this spec's filter, wrap, shadow-compare, and mipmap parameters to
     * the currently bound texture at {@code target}.
     *
     * <p>Wrap-R is only written for 3D ({@code GL_TEXTURE_3D}) and
     * 2D-array ({@code GL_TEXTURE_2D_ARRAY}) targets.</p>
     *
     * <p>Shadow comparison params are written only when {@link #compareMode} is not
     * {@code GL_NONE}.</p>
     *
     * <p>If the spec has mipmap config enabled, min/mag filters are overridden with
     * the mipmap-aware filters and {@code glGenerateMipmap} is called.</p>
     */
    public void applyTo(int target) {
        GL11.glTexParameteri(target, GL11.GL_TEXTURE_MIN_FILTER, minFilter);
        GL11.glTexParameteri(target, GL11.GL_TEXTURE_MAG_FILTER, magFilter);
        GL11.glTexParameteri(target, GL11.GL_TEXTURE_WRAP_S, wrapS);
        GL11.glTexParameteri(target, GL11.GL_TEXTURE_WRAP_T, wrapT);
        // Wrap-R is only meaningful for 3D and 2D-array targets.
        if (target == GL12.GL_TEXTURE_3D || target == GL30.GL_TEXTURE_2D_ARRAY) {
            GL11.glTexParameteri(target, GL12.GL_TEXTURE_WRAP_R, wrapR);
        }
        // Shadow comparison — only when explicitly enabled (DEPTH24_SHADOW etc.)
        if (compareMode != GL11.GL_NONE) {
            GL11.glTexParameteri(target, GL14.GL_TEXTURE_COMPARE_MODE, compareMode);
            GL11.glTexParameteri(target, GL14.GL_TEXTURE_COMPARE_FUNC, compareFunc);
        }
        // Mipmap — override min/mag filter and generate mip chain
        if (mipmaps != null && mipmaps.isEnabled()) {
            GL11.glTexParameteri(target, GL11.GL_TEXTURE_MIN_FILTER, mipmaps.getMinFilter());
            GL11.glTexParameteri(target, GL11.GL_TEXTURE_MAG_FILTER, mipmaps.getMagFilter());
            GL30.glGenerateMipmap(target);
        }
    }
}
